### PR TITLE
Fix no previous tag when using get cmd

### LINKED ISSUE #144: Full Changelog in GitHub Release too broad
Hi @chelnak, we noticed an issue raised in our repos that had to do with unexpected behaviour with full changelog generation, so we wanted to make you aware of this.

## Describe the Bug
When the Module Release workflow generates a new GitHub Release, it includes a "Full Changelog" link that shows every commit between the first commit in the repo and the current release.

This differs from the CHANGELOG.md generated from the Module Release Prep workflow, which also includes a "Full Changelog" link but only shows the commits between the previous and current releases.

## Expected Behavior
I would expect the changelog in a GitHub Release to show a more limited range of changes, or maybe omit the "Full Changelog" link altogether. Many Ruby projects do not include such a link, not all users are interested in just the changes between the two latest releases, and GitHub's UI provides a way to compare the changes between a release and any tag or branch.

For reference, this is the result we would expect: https://github.com/puppetlabs/puppetlabs-apt/compare/v9.2.0...v9.4.0
And this is the actual result appearing: https://github.com/puppetlabs/puppetlabs-apt/compare/f848bac6072f99e1cd60a0cc0b84e5679c598dab...v9.4.0

## Steps to Reproduce
Click on the "Full Changelog" link in any GitHub Release generated by the Module Release workflow (such as here: https://github.com/puppetlabs/puppetlabs-apt/releases/tag/v9.4.0).

## Additional Context
This was originally reported in the Puppet community Slack: https://puppetcommunity.slack.com/archives/C11LCKKQ9/p1709771123022279

### PR DESCRIPTION
**Pull request by h0tw1r3**
Fixes #144

### CODE REVIEW

**Comment by chelnak** [comment]
@h0tw1r3 thank you for the contribution!

I've been holding off on a release while I investigate #145 however it's taking a little longer thank I expected to finish.

Let's get this merged and I can cut a release today.

**Review by chelnak — APPROVED** [review]

**Comment by h0tw1r3** [comment]
@chelnak Took another look this morning, looks like there's a panic on `get --latest` when there's only one entry in the changelog. Working on a fix.

**Comment by chelnak** [comment]
Oh nice, is it there when you pull the latest release? I fixed a panic in the parser.. maybe it's related?

**Comment by h0tw1r3** [comment]
Yes, pretty obvious bug. Should have been sleeping instead of coding 🤣

**Pull request merged**
